apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql-remapped
  namespace: pgns
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.6
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:17.2
    - major: 17
      image: ghcr.io/mattiarossi/postgresql@sha256:23d597712c885e3b1dd250c7826c6acf1736d9dee39584b5a271c0bcbe3e11a0
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-mr1
  namespace: pgns
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql-remapped
    major: 17  
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: hpe-storageclass  
  enableSuperuserAccess: true  
  monitoring:
    enablePodMonitor: true    
  backup:
    volumeSnapshot: 
      className: "hpe-snapshot"
