apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-mr2
  namespace: pgns
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql-remapped
    major: 17  
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: hpe-storageclass  
  enableSuperuserAccess: true  
  monitoring:
    enablePodMonitor: true    
  backup:
    volumeSnapshot: 
      className: "hpe-snapshot"
  managed:
    services:
      disabledDefaultServices: []
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: cluster-mr2-rw-lb
          spec:
            type: NodePort
      
