apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql-remapped
  namespace: pgns
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.6
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:17.2
    - major: 17
      image: ghcr.io/mattiarossi/postgresql:17.2-cron-plv8-pgaudit--202502101725
---
